/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Contributors:
 *               Bademus
 */

package org.github.bademux.feedly.api.oauth2;

import com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest;
import com.google.api.client.auth.oauth2.TokenResponse;
import com.google.api.client.auth.oauth2.TokenResponseException;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpExecuteInterceptor;
import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.util.Preconditions;

import java.io.IOException;
import java.util.Collection;

/**
 * Feedly-specific implementation of the OAuth 2.0 request for an access token based on an
 * authorization code (as specified in <a href="http://code.google.com/apis/accounts/docs/OAuth2WebServer.html">Using
 * OAuth 2.0 for Web Server Applications</a>).
 *
 * <p> Use {@link com.google.api.client.auth.oauth2.Credential} to access protected resources from
 * the resource server using the {@link TokenResponse} returned by {@link #execute()}. On error, it
 * will instead throw {@link TokenResponseException}. </p>
 *
 * <p> Sample usage: </p>
 *
 * <pre>
 * static void requestAccessToken() throws IOException {
 * try {
 * FeedlyTokenResponse response =
 * new FeedlyAuthorizationCodeTokenRequest(new NetHttpTransport(), new JacksonFactory(),
 * "812741506391.apps.googleusercontent.com", "{client_secret}",
 * "4/P7q7W91a-oMsCeLvIaQm6bTrgtp7", "https://oauth2-login-demo.appspot.com/code")
 * .execute();
 * System.out.println("Access token: " + response.getAccessToken());
 * } catch (TokenResponseException e) {
 * if (e.getDetails() != null) {
 * System.err.println("Error: " + e.getDetails().getError());
 * if (e.getDetails().getErrorDescription() != null) {
 * System.err.println(e.getDetails().getErrorDescription());
 * }
 * if (e.getDetails().getErrorUri() != null) {
 * System.err.println(e.getDetails().getErrorUri());
 * }
 * } else {
 * System.err.println(e.getMessage());
 * }
 * }
 * }
 * </pre>
 *
 * <p> Implementation is not thread-safe. </p>
 */
public class FeedlyAuthorizationCodeTokenRequest extends AuthorizationCodeTokenRequest {

  /**
   * @param transport             HTTP transport
   * @param jsonFactory           JSON factory
   * @param tokenServerEncodedUrl token server encoded URL
   * @param code                  authorization code generated by the authorization server
   */
  public FeedlyAuthorizationCodeTokenRequest(HttpTransport transport, JsonFactory jsonFactory,
                                             String tokenServerEncodedUrl, String code) {
    super(transport, jsonFactory, new GenericUrl(tokenServerEncodedUrl), code);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setRequestInitializer(
      HttpRequestInitializer requestInitializer) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setRequestInitializer(requestInitializer);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setTokenServerUrl(GenericUrl tokenServerUrl) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setTokenServerUrl(tokenServerUrl);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setScopes(Collection<String> scopes) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setScopes(scopes);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setGrantType(String grantType) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setGrantType(grantType);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setClientAuthentication(
      HttpExecuteInterceptor clientAuthentication) {
    Preconditions.checkNotNull(clientAuthentication);
    return (FeedlyAuthorizationCodeTokenRequest) super.setClientAuthentication(
        clientAuthentication);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setCode(String code) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setCode(code);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setRedirectUri(String redirectUri) {
    Preconditions.checkNotNull(redirectUri);
    return (FeedlyAuthorizationCodeTokenRequest) super.setRedirectUri(redirectUri);
  }

  @Override
  public FeedlyTokenResponse execute() throws IOException {
    return executeUnparsed().parseAs(FeedlyTokenResponse.class);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest set(String fieldName, Object value) {
    return (FeedlyAuthorizationCodeTokenRequest) super.set(fieldName, value);
  }
}
