/*
 * Copyright 2013 Bademus
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *    Contributors:
 *                 Bademus
 */

package org.github.bademux.feedly.api.oauth2;

import com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest;
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpExecuteInterceptor;
import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.json.JsonFactory;
import com.google.api.client.util.Preconditions;

import java.io.IOException;
import java.util.Collection;

/**
 * @inheritDoc
 */
public class FeedlyAuthorizationCodeTokenRequest extends AuthorizationCodeTokenRequest {

  /**
   * @param transport             HTTP transport
   * @param jsonFactory           JSON factory
   * @param tokenServerEncodedUrl token server encoded URL
   * @param code                  authorization code generated by the authorization server
   */
  public FeedlyAuthorizationCodeTokenRequest(HttpTransport transport, JsonFactory jsonFactory,
                                             String tokenServerEncodedUrl, String code) {
    super(transport, jsonFactory, new GenericUrl(tokenServerEncodedUrl), code);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setRequestInitializer(
      HttpRequestInitializer requestInitializer) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setRequestInitializer(requestInitializer);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setTokenServerUrl(GenericUrl tokenServerUrl) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setTokenServerUrl(tokenServerUrl);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setScopes(Collection<String> scopes) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setScopes(scopes);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setGrantType(String grantType) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setGrantType(grantType);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setClientAuthentication(
      HttpExecuteInterceptor clientAuthentication) {
    Preconditions.checkNotNull(clientAuthentication);
    return (FeedlyAuthorizationCodeTokenRequest) super.setClientAuthentication(
        clientAuthentication);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setCode(String code) {
    return (FeedlyAuthorizationCodeTokenRequest) super.setCode(code);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest setRedirectUri(String redirectUri) {
    Preconditions.checkNotNull(redirectUri);
    return (FeedlyAuthorizationCodeTokenRequest) super.setRedirectUri(redirectUri);
  }

  @Override
  public FeedlyTokenResponse execute() throws IOException {
    return executeUnparsed().parseAs(FeedlyTokenResponse.class);
  }

  @Override
  public FeedlyAuthorizationCodeTokenRequest set(String fieldName, Object value) {
    return (FeedlyAuthorizationCodeTokenRequest) super.set(fieldName, value);
  }
}
